### PR TITLE
Create reverseflashdanielwest.ms

### PR DESCRIPTION
**Pull request by Leedler268**

### CODE REVIEW

**Comment by mythguy1226** [comment]
line 27 replace the period with a comma

**Comment by Leedler268** [comment]
He has electrokinesis abilities, shown in this pic: https://static.comicvine.com/uploads/original/11127/111271893/5567662-5991381316-41235.jpg\
Also metal manipulation of the metal on his suit: https://vignette4.wikia.nocookie.net/marvel_dc/images/6/68/Flash_Vol_4_23.2_Reverse-Flash_Textless.jpg/revision/latest?cb=20130911194209
He has claws, but I don't think that it is necessary.

**Comment by malonnnn** [comment]
I have removed /thru /whirlwind /lightning and /ma due to lack of proof

**Comment by Leedler268** [comment]
He can manipulate metal as shown in the pic in the comment above yours.
He has electrokinesis abilities as well.https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjMn7mw6KnUAhUBSRoKHQOcCgwQjBwIBA&url=https%3A%2F%2Fimages.moviepilot.com%2Fimages%2Fc_limit%2Cq_auto%3Agood%2Cw_600%2Frxscbasvw2ye6jcsmtfr%2Fthat-s-barry-allen-against-daniel-west.jpg&psig=AFQjCNEA2Nmv_quCxy7H7Y1JAI_VssbS8A&ust=1496858977430177
Isn't that proof? Also in this pic: https://static.comicvine.com/uploads/original/14/149570/3283537-img_7157.pngc
I understand /whirlwind but not /thru. Although there is no extensive proof, if you go on the DC wiki page, you can see that he can phase through solid objects. Same with the other abilities except for /whirlwind. Please read this comment.

**Comment by Leedler268** [comment]
It appears that this is him stealing speed that is why sprint is like "what?"
: https://static.comicvine.com/uploads/original/14/149570/3283537-img_7157.png

**Comment by Leedler268** [comment]
He's also manipulating metal

**Pull request merged**
