### PR TITLE
Create buffythevampslayer.ms

### PR DESCRIPTION
**Pull request by boogernut**

### CODE REVIEW

**Comment by mythguy1226** [comment]
get rid of the empty lines which are 19, 20, and 30

**Comment by mythguy1226** [comment]
now get rid of line 28

**Comment by mythguy1226** [comment]
get rid of the comma at the end of line 18

**Comment by boogernut** [comment]
https://static.comicvine.com/uploads/original/11113/111131174/3399732-buffy+feat+strength+carries+guy+up+fire+escape.jpg    that is proof of her super strength

**Comment by boogernut** [comment]
https://static1.comicvine.com/uploads/square_medium/14/147508/5546624-buffy+vs+vampires+%2354+%282%29.png buffy using super speed

**Comment by boogernut** [comment]
http://buffy.wikia.com/wiki/Buffy_Summers#Powers_and_Abilities proof of all buffy's powers

**Pull request closed without merging**
