### PR TITLE
Update perms for greninja

### PR DESCRIPTION
**Pull request by ThisChicken**
he dies when he jumps at full power

### CODE REVIEW

**Comment by malonnnn** [comment]
you have not provided any evidence of these powers

**Comment by ThisChicken** [comment]
https://www.youtube.com/watch?v=YkdqFIsAYcg
at 3:36 he jumps high into the air and he comes down unharmed

**Comment by malonnnn** [comment]
Hm, I don't think I can agree to this, that jump is only like 10-15 feet in the air, even a human can do that. Do you have any other evidence?

**Comment by ThisChicken** [comment]
https://www.youtube.com/watch?v=f_hIe16YSIw
at 2:11 he falls and continues fighting

**Comment by malonnnn** [comment]
okay the fell for about 1 second, and since gravity is 9.8 m/s, that means he fell 32 feet. impressive, but he can already do that

**Comment by ThisChicken** [comment]
https://www.youtube.com/watch?v=YkdqFIsAYcg&t=284s he jumps and stayes in the air at 0:48 + he moves at 1:08. Proof of flight

**Comment by malonnnn** [comment]
this seems more like artistic measure than ability to fly.

show him flying over some buildings or something, not just hovering and moving a bit in a cave

**Comment by ViceTOP** [comment]
Pokemon that are not flying type pokemon, can stay in the air for a few seconds, this has been seen for a while, but it isnt flying, it's just so it looks more cool lol

**Pull request closed without merging**
