### PR TITLE
Create indigolanternindigoone.ms

### PR DESCRIPTION
**Pull request by ViceTOP**

### CODE REVIEW

**Comment by ZargonKing** [comment]
TONs of commands are in incorrect format

**Comment by ViceTOP** [comment]
Ik, I realized last night, but had to go so woke up soon and checked all my files for errors :P

**Comment by malonnnn** [comment]
if this is in relation to green lantern, classname should be

**greenlanternindigoone**
and names should be
**Green Lantern-I1**

**Comment by ViceTOP** [comment]
indigo is their own lantern corp, Indigo Lanterns aka Indigo Tribe

**Comment by malonnnn** [comment]
since indigo 1 is part of another Corps called The Indigo Tribe, they will be to be named as such since there are multiple members.

Suggestions:
theindigotribeindigoone
The Indigo Tribe-I1

**Pull request merged**
