### PR TITLE
Update flashwallywest.ms

### PR DESCRIPTION
**Pull request by MrCraft888**

### CODE REVIEW

**Comment by malonnnn** [comment]
please link the skin you are updating

**Comment by MrCraft888** [comment]
http://www.planetminecraft.com/skin/wally-west-3819254/

**Comment by malonnnn** [comment]
what comic is this from?

**Comment by MrCraft888** [comment]
its from YJ

**Comment by malonnnn** [comment]
i tried googling, but i dont see him wearing anything like that. can you find a pic?

**Comment by MrCraft888** [comment]
http://vignette2.wikia.nocookie.net/theflash/images/1/1b/Young_Justice_-_Performance.jpg/revision/latest?cb=20120724205832

**Comment by malonnnn** [comment]
he needs to be shown going fast in whatever suit he's wearing. its known that casual clothes cannot hold up to fast speeds

**Comment by MrCraft888** [comment]
ok so if i cant find one ill delete this code k

**Comment by malonnnn** [comment]
that sounds okay to me mrcraft

**Pull request closed without merging**
