### PR TITLE
Update permissions.yml

### PR DESCRIPTION
**Pull request by ZargonKing**

### CODE REVIEW

**Comment by ZargonKing** [comment]
https://www.youtube.com/watch?v=LKx1MuxOSv8
https://www.youtube.com/watch?v=L0D0VGomWb4
http://comicvine.gamespot.com/forums/gen-discussion-1/a-closer-look-at-superman-prime-one-million-1642666/
http://comicvine.gamespot.com/mr-mxyzptlk/4005-27436/
http://i.imgur.com/C2gUppf.jpg
http://s238.photobucket.com/user/Galan_photos/media/wf4.jpg.html
http://i.imgur.com/dkVaWJu.jpg
https://www.reddit.com/r/respectthreads/comments/232zyg/thanos/
http://comicvine.gamespot.com/forums/gen-discussion-1/thought-robotcosmic-armor-superman-respect-thread--1704259/
https://www.reddit.com/r/respectthreads/comments/2fpjiq/respect_the_silver_surfer/

**Comment by ViceTOP** [comment]
Neither of those are official from DC or Marvel.

**Comment by ViceTOP** [comment]
I mean the websites, if there is a comic image good

**Comment by ViceTOP** [comment]
Why are they even kill immune

**Comment by ViceTOP** [comment]
Since when can Infinity Thanos kill magically?

**Comment by ViceTOP** [comment]
Proof of any of them changing their appearance to someone else OR an animal?

**Comment by ViceTOP** [comment]
Are all of them omnipresence? or can appear in any place at anytime?

**Comment by ViceTOP** [comment]
Do they all have mind powers to control or speak through someone?

**Comment by ViceTOP** [comment]
Can they share their power?

**Comment by ViceTOP** [comment]
Can they summon lightning?

**Comment by ZargonKing** [comment]
Silver Surfer proofs:

Transmutation ability:
http://i.imgur.com/mKXPx0z.jpg
http://i.imgur.com/ZdyVZ5v.jpg
http://i.imgur.com/lxGjRmy.jpg

Speed is insanely fast (offensive and passive):
http://i.imgur.com/HTuXrL5.jpg
http://i.imgur.com/sBZfSjv.jpg
http://i.imgur.com/VozAkj8.jpg
http://i.imgur.com/t00UZV7.jpg
http://i.imgur.com/p3sWez4.jpg
http://i.imgur.com/4Romgl3.jpg

Ability to morph into someone else or change someone's appearance:
http://i.imgur.com/oH4oqJJ.jpg

Is psychic and has cosmic awareness:
http://i.imgur.com/uIGILkv.jpg
http://i.imgur.com/oEXFNch.jpg
http://imgur.com/a/QYazx#0
http://i.imgur.com/5pDLa0x.jpg
http://i.imgur.com/Cu3FAGe.jpg
http://i.imgur.com/COx3NA3.jpg
http://i.imgur.com/wlANSFw.jpg
http://i.imgur.com/SrnAhPB.jpg
http://i.imgur.com/RzyC1Jo.jpg
http://i.imgur.com/5NpOEOP.jpg
http://i.imgur.com/JVQjJ99.jpg
http://i.imgur.com/9EtFIOL.jpg

**Comment by ZargonKing** [comment]
Infinity Thanos proofs:

Becoming omnipresent:
https://s-media-cache-ak0.pinimg.com/564x/7d/a4/d1/7da4d1d0e5975c1e120ff0350a5e561e.jpg

defeating The One Above All:
http://static1.comicvine.com/uploads/original/11112/111128749/5121204-3320367344-429cd.jpg

able to take hits from combined powers of odin and silver surfer:
https://s-media-cache-ak0.pinimg.com/236x/d3/e3/26/d3e326afd37b1badcbf9a668c4affdb3.jpg

Able to teleport others away from him:
http://static.comicvine.com/uploads/original/15/150339/2972814-7642197659-thano.jpg

Able to withstand the Shouts of Black Bolt:
http://static.comicvine.com/uploads/original/13/137152/3441291-1.png
http://i1007.photobucket.com/albums/af191/lgu88/Infinity003-029_zps0bb0c5de.jpg
http://i118.photobucket.com/albums/o106/bigbran1/Thanos/Infinity004-013.jpg
https://www.gonnageek.com/wp-content/uploads/2013/10/Infinity-04-02.png
http://static.comicvine.com/uploads/original/10/103729/3539014-7114321130-33641.jpg

**Comment by ZargonKing** [comment]
Mr Mxyzptlk proofs:

A quick summary of the fifth dimensional imp(apparently this is canon):
http://i.imgur.com/XNg901L.jpg

Luthor's evaluation on this imp:
http://i.imgur.com/P2kMuMC.jpg

**Comment by ViceTOP** [comment]
The images you put was Thanos with the heart of the universe.

**Comment by ZargonKing** [comment]
Cosmic Armor Superman proofs:

He is omnipresent (why do I say that?):

1.He can feel the story and narratives around him.Even the reader of the comic too!
http://i.imgur.com/D4aSGgd.png
http://i.imgur.com/NoVaykz.png

2.Exists outside the multiverses and able to perceive Limbo from the outside
http://i.imgur.com/U95M5Gx.png

3.Able to hear the heartbeat of Lois universes away:
http://i.imgur.com/nrBcnr0.jpg

4.Perceive the true nature of the Monitors:
http://i.imgur.com/R8iXrLV.png

5. Hear Mandrakk scream even though he no longer exists
http://i.imgur.com/Kf1fCMv.png


Combat prowesses:
http://i.imgur.com/YW1kYKT.png
http://i.imgur.com/axw2KEd.png
http://i.imgur.com/ix9oMyn.jpg
http://i.imgur.com/myZCk4L.png

**Comment by ViceTOP** [comment]
Make them killable

**Comment by ViceTOP** [comment]
And about Cosmic Armor SUperman, those are all theories.

**Pull request merged**
