### PR TITLE
Kirito.ms

### PR DESCRIPTION
**Pull request by Kirigia**

### CODE REVIEW

**Comment by mythguy1226** [comment]
kirito should not be capitalized

**Comment by Kirigia** [comment]
so i uncapitalize everything?

**Comment by mythguy1226** [comment]
uncapitalize the file name and the line with class: Kirito

**Comment by Kirigia** [comment]
ok all done

**Comment by mythguy1226** [comment]
line 6 Kirito must also be uncapitalized

**Comment by mythguy1226** [comment]
line 16 and 24 should not have commas at the end

**Comment by Kirigia** [comment]
proof for speed:
https://www.youtube.com/watch?v=m1BcU8CDzGI
just skip to 2:23 for speed.
Proof of haste:
https://www.youtube.com/watch?v=MBERAvGtJtg
go to 2:22... just enjoy it and he get's faster.
proof of strength:
https://www.youtube.com/watch?v=PVahfwrn39o
skip to 1:22. might be a different game but his stats are the same so there's no difference.
proof of regen:
just go back to the first video and find the part where he explains his regeneration
proof of health boost:
first video, also where he explains his healing.
proof of resistance:
pretty self explanatory as 10 guys tryna kill one dude without the one guy flinching in the first vid... ye
proof of his weapons:
Elucidator:
https://www.youtube.com/watch?v=xd3e4GY29FY
Dark repulser:
https://www.youtube.com/watch?v=AFv-g3wT4hM
excalibur:
https://www.youtube.com/watch?v=UD7ZfZJxMzg
if you wanna see the weapon's effectiveness go to the haste video.
finally more on kirito's speed:
https://www.youtube.com/watch?v=av6AG-8RKcg
ok all the proof :)

**Comment by malonnnn** [comment]
This file is supposed to be in CommandHelper/LocalPackages/commands/buffs/kirito.ms

Instead it's not inside any folder, it's in the root directory

**Pull request closed without merging**
