### PR TITLE
Update templates.yml

### PR DESCRIPTION
**Pull request by IdkMyNamePleaseTellMe**
wondergirldt

### CODE REVIEW

**Comment by ItzHarkomal** [comment]
In line 21, there should only be one space before your name. Also, change _WonderBat_ to all lowercase letters.

**Comment by ItzHarkomal** [comment]
In line 23, make your name to all lowercase letters.

**Comment by ItzHarkomal** [comment]
In line 22 and 28 it should be like this: c8b88131-52d4-4af0-9593-ddcdb3d56058 With dashes.

**Comment by mythguy1226** [comment]
press enter at the end of line 9199

**Comment by mythguy1226** [comment]
sorry I meant 9169

**Comment by mythguy1226** [comment]
try doing it at the bottom of the file

**Comment by mythguy1226** [comment]
delete the empty line on 9170, 9201, and 9202

**Pull request closed without merging**
