### PR TITLE
Create blackflash.ms

### PR DESCRIPTION
**Pull request by Richinator324**

### CODE REVIEW

**Comment by malonnnn** [comment]
missing speedforce powers

**Comment by malonnnn** [comment]
should probably add a powers letting them know they can use /run 0 and /run 1 in the speedforce

**Comment by Richinator324** [comment]
What do you mean by that? I don't see anything like that on any of the other speedsters.

**Comment by malonnnn** [comment]
go change into barry allen and do /powers, you will see what i mean

**Pull request merged**
