### PR TITLE
Create thedoctor.ms

### PR DESCRIPTION
**Pull request by GrayHat4Life**
Adds The Doctor from Doctor Who. This is the first superhero submission by nevsfam.

### CODE REVIEW

**Comment by flamingwarrior10** [comment]
where are permissions and skin for machine

**Comment by malonnnn** [comment]
please show a link to the skin you used

**Comment by GrayHat4Life** [comment]
Here's the skin: http://www.planetminecraft.com/skin/4th-doctor--tom-baker-doctor-who-50th-anniversary-skin-series/
I updated the permissions file to allow the Doctor to use his powers. I'm having a bit of trouble making a pull request for the permissions file, but it should be done soon

**Comment by GrayHat4Life** [comment]
Okay, the permissions for the Doctor are on line #5954 of the edited file, but I'm still having trouble with the pull request. My week's about to start, so I may not get this done soon

**Comment by GrayHat4Life** [comment]
I DID IT!!! Okay, so the permissions file update is now in the pull requests. I hope this fixes the problems we've been having.

Just a heads up: I may not be able to check back for a day at least, but I will check back ASAP

**Comment by GrayHat4Life** [comment]
I'm going to watch the video on creating skins for the machine and I should have that done in a few days at most.

**Comment by malonnnn** [comment]
the sonic screwdriver won't compile, the quotations marks are messed up.

I would suggest just removing it

**Pull request merged**
