### PR TITLE
Update permissions.yml SquirrelGirl

### PR DESCRIPTION
**Pull request by flamingwarrior10**
kk

### CODE REVIEW

**Comment by malonnnn** [comment]
the squirrelgirl permission node is spaced way wrong. compare it to other heroes to see whats wrong better

**Comment by malonnnn** [comment]
the title says "Update permissions.yml"....who is this update for?

**Comment by malonnnn** [comment]
please update the title, it still just says "update permissions.yml"

**Comment by malonnnn** [comment]
you accidentally renamed the file instead of the title of the pull request xD

**Comment by flamingwarrior10** [comment]
am i good tho?

**Comment by flamingwarrior10** [comment]
there

**Comment by malonnnn** [comment]
this file needs to be named "permissions.yml" not "PermissionsEx/Squirrel Girl perms"

xD i still luv u bro

**Comment by flamingwarrior10** [comment]
luv u too

**Comment by malonnnn** [comment]
it should be permissions.yml not Permissions.yml

case matters :\

**Comment by malonnnn** [comment]
should be & signs in the prefix, not section signs. section signs are only for the .ms file

**Comment by flamingwarrior10** [comment]
ok

**Comment by malonnnn** [comment]
Her name is Squirrel Girl, not squirrelgirl xD

**Comment by malonnnn** [comment]
forgot to capitalize her name xD

**Pull request merged**
